stages:
  - deploy

variables:
  # 환경 변수 설정
  PM2_APP_NAME: "index" # PM2에서 사용할 애플리케이션 이름

deploy_dev:
  stage: deploy
  only:
    - dev # dev 브랜치에 변경 사항이 있을 때만 실행
  script:
    - eval $(ssh-agent -s) # SSH 에이전트 활성화
    - ssh-add ~/.ssh/id_rsa # SSH 개인 키 추가
    - git pull
    - npm install
    - pm2 restart $PM2_APP_NAME
