// 토큰 상수들을 적어놓음

const LOGIN_REQUEST = "USER_LOGIN_REQUEST";
const LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
const LOGIN_FAIL = "USER_LOGIN_FAIL";
const LOGOUT = "USER_LOGOUT";
const GOOGLE_LOGIN_REQUEST = "GOOGLE_LOGIN_REQUEST";
const GOOGLE_LOGIN_SUCCESS = "GOOGLE_LOGIN_SUCCESS";
const GOOGLE_LOGIN_FAIL = "GOOGLE_LOGIN_FAIL";
const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";
const LOGIN_AS_TOKEN_REQUEST = "LOGIN_AS_TOKEN_REQUEST";
const LOGIN_AS_TOKEN_SUCCESS = "LOGIN_AS_TOKEN_SUCCESS";
const LOGIN_AS_TOKEN_FAIL = "LOGIN_AS_TOKEN_FAIL";

module.exports = {
    LOGIN_REQUEST,
    LOGIN_SUCCESS,
    LOGIN_FAIL,
    LOGOUT,
    GOOGLE_LOGIN_REQUEST,
    GOOGLE_LOGIN_SUCCESS,
    GOOGLE_LOGIN_FAIL,
    REGISTER_USER_REQUEST,
    REGISTER_USER_SUCCESS,
    REGISTER_USER_FAIL,
    LOGIN_AS_TOKEN_REQUEST,
    LOGIN_AS_TOKEN_SUCCESS,
    LOGIN_AS_TOKEN_FAIL
};
